### ISSUE TITLE
Cannot produce tabulated list.

### ISSUE THREAD

**Issue by litsol** [ousia/handlecsv#3]
The following code works, with complaints, with a ConTeXt version from 2018.10.18. It does not work with the current release. The sample code from your project page works as advertised. I used it to try various alternatives, including natural tables, but tabulations yield only the first row and table values are all nil. As you see, I merely want to produce a tabulated list. Any assistance or guidance you can give will be greatly appreciated.

\usemodule[handlecsv]
\setuppapersize[A4,landscape]
\switchtobodyfont[10pt]
\opencsvfile{sample.csv}
\starttext
  \startbuffer[loop]
    \NC \cE \NC \cG \NC \cI \NC \cJ \NC \cT \NC\NR
  \stopbuffer
  \starttabulate[|l|l|l|l|lp|]
    \doloopforall{\getbuffer[loop]}
  \stoptabulate
\stoptext

**Comment by ousia** [comment]
@litsol,

the following code works fine:

``` tex
\usemodule[handlecsv]
\opencsvfile{sample.csv}
\setupbodyfont[palatino]
\starttext
\startbuffer[loop]
    \startxrow
        \startxcell\cA\stopxcell
        \startxcell\cB\stopxcell
        \startxcell\cA\stopxcell
        \startxcell\cC\stopxcell
        \startxcell\cB\stopxcell
    \stopxrow
\stopbuffer
\startxtable
\doloopif{\cB}{~=}{}{\getbuffer[loop]}
\stopxtable
\stoptext
```

given the following contents in `sample.csv`:

``` csv
"α";"a";1;"I"
"β";"b";2;"II"
"α";"a";3;"III"
"β";"b";4;"IV"
"α";"a";5;"V"
"β";"b";6;"I"
"α";"a";7;"II"
"β";"b";8;"III"
"α";"a";9;"IV"
"β";"b";10;"V"
"α";"a";11;"I"
"β";"b";12;"II"
"α";"a";13;"III"
"β";"b";14;"IV"
```

I‘m afraid I never used `tabulate`. Would `xtables` work for you?

**Comment by litsol** [comment]
Dear Pablo,

Yes, xtables will suite me very well. Thank you for your example and your
speedy response.

With kind regards,

Michael Guravage

**Comment by ousia** [comment]
Glad to hear it helped.

I’m closing the issue.
