### ISSUE TITLE
Accept variable (macro) for filename in \opencsv

### ISSUE THREAD

**Issue by Amphiboly** [ousia/handlecsv#5]
I would like to pass the csv filename from the command line via the documentargument mechanism. This works to get the filename into ConTeXt, but it appears that the lua code invoked by \opencsv expects a literal filename, and the processing abends.

Can \opencsv be updated to accept a macro instead of a literal?

**Comment by ousia** [comment]
> Can `\opencsv` be updated to accept a macro instead of a literal?

@Amphiboly,

many thanks for your report.

The following code works for me:

``` tex
\usemodule[handlecsv]

\def\smp{sample.csv}
\opencsvfile{\smp}
```

> I would like to pass the csv filename from the command line via the documentargument mechanism.

Not sure what you mean. Could you provide a minimal sample of what isn’t working?

Sorry, but I’m afraid that https://github.com/ousia/handlecsv/issues/4#issuecomment-1019448976 still applies.

**Comment by Amphiboly** [comment]
My fault. I had tried \define, should have used \defineexpandable. All is well.
